# Generated by Django 5.2.4 on 2025-09-03 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_product_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='helpful_by',
            field=models.ManyToManyField(blank=True, related_name='helpful_product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='helpful_by',
            field=models.ManyToManyField(blank=True, related_name='helpful_shop_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
