# Generated by Django 5.2.4 on 2025-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('clothes', 'Clothes'), ('electronics', 'Electronics'), ('fastfood', 'Fast Food'), ('beauty', 'Beauty Product'), ('medicine', 'Medicine'), ('home_appliance', 'Home Appliance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('food_delivery', 'Food & Delivery'), ('beauty', 'Beauty & Personal Care'), ('home', 'Home & Furniture'), ('pharmacy', 'Pharmacy & Wellness'), ('sports', 'Sports & Fitness')], max_length=50),
        ),
    ]
