# Generated by Django 5.2.4 on 2025-09-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_product_type_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner'), ('ADMIN', 'Admin'), ('DELIVERY_BOY', 'Delivery Boy')], default='CUSTOMER', max_length=20),
        ),
    ]
