# Generated by Django 5.2.4 on 2025-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_user_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage for this shop', max_digits=5),
        ),
    ]
