# Generated by Django 5.2.4 on 2025-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_shop_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SHOP_OWNER', 'Shop Owner'), ('ADMIN', 'Admin'), ('DELIVERY_BOY', 'Delivery Boy')], max_length=20, null=True),
        ),
    ]
